version: '3.9'

services:
  backend:
    build:
      context: ..
      dockerfile: dockerfile/Dockerfile
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:1234@mysql:3306/instagram
    depends_on:
      - mysql
    volumes:
      - ../backend:/app/backend
    networks:
      - flask_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: instagram
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flask_network

volumes:
  mysql_data:

networks:
  flask_network:
